<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
	<PackageId>victor-wiki.$(AssemblyName)</PackageId>
    <Version>1.0.0</Version>
    <PackageReleaseNotes></PackageReleaseNotes>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <RepositoryUrl>https://github.com/victor-wiki/TorchSharp</RepositoryUrl>
    <Description>This project is fork from https://github.com/dotnet/TorchSharp and make some changes. </Description>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LibTorchSharp.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <PackagePath>lib\net10.0</PackagePath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.0" />
    <PackageReference Include="libtorch-cpu" Version="2.10.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
  </ItemGroup>

</Project>
